### ISSUE TITLE
data type of transaction quota in blockchain.proto

### ISSUE THREAD

**Issue by QingyangKong** [cryptape/cita-proto#9]
The datatype of quota in transaction is uint64, and it means the max quota user allowed to set in a transaction is 0xFFFFFFFFFFFFFFFF that is 18.446744073709551615e18 in decimal. In the scenario, the limit of quota for user is about 18.4 NOS. Although almost no one would set this amount for quota in a transaction, I am wondering if we should set a limit for quota in a transaction.   
Do we have a plan to convert datatype of quota from uint64 to bytes in the future or we decide to set a quota limit for transactions.

**Comment by kaikai1024** [comment]
It always check block quota limit. 
If you set the `checkQuota=true`, will check account quota limit
